package lexer.token;

public enum TokenType {
    INT, BEGIN, END, FUNCTION, IF, ELSE, FOR, GOES, FROM, TO, CALL, RETURN,
    // OR,
    IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN, COLON,
    NEWLINE, REDSTONE, GOLD, DIAMOND, EMERALD, IRON, CHAIN, CHEST, MINE, DROP, COLLECT, DIG, LOOT, EOF,
    DEEPER, BEDROCK, CRAFT, BUILD, DO, FORTRESS, EXTENDS, POWERED, UNPOWERED, AND, OR, LBRACE, RBRACE, QUESTION, SEMICOLON, NOT, LSHIFT, RSHIFT, BIT_AND, BIT_OR,

}
